# Generated by Django 5.0 on 2024-01-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicVenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=2000)),
                ("address", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField()),
                ("check_out", models.DateTimeField()),
                ("username", models.CharField(max_length=100)),
                (
                    "music_venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="booking.musicvenue",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="musicvenue",
            name="services",
            field=models.ManyToManyField(
                to="booking.service", verbose_name="available services"
            ),
        ),
    ]
