# Generated by Django 5.0 on 2024-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
